import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Dancing_Script } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { currentUser } from "@clerk/nextjs/server";
import { SignedIn, UserButton } from "@clerk/nextjs";
import Cart from "@/components/custom/cart";
const dancing_Script = Dancing_Script({
  weight: "500",
  subsets: ["latin"],
});
const poppins = Poppins({
  weight: "300",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mai Jidda Table Water",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let isAdmin = (await currentUser())?.publicMetadata.isAdmin === true;
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body className={`${poppins.className} flex justify-center mt-5 antialiased`}>
          <div className="w-[80%]">
            <header className="flex justify-between  text-blue-950">
              <div className={`${dancing_Script.className} logo w-[60%] text-3xl `}>Mai Jidda</div>
              <div className="info flex justify-end w-[40%]">
                {!isAdmin ? (
                  <div className="cart cursor-pointer">
                    <Cart />
                  </div>
                ) : (
                  ""
                )}
                <div className="profile-item ml-5">
                  <SignedIn>
                    <UserButton />
                  </SignedIn>
                </div>
              </div>
            </header>
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
